apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
      annotations:
        vault.hashicorp.com/agent-inject: "true"
        vault.hashicorp.com/role: "myapp-role"
        vault.hashicorp.com/agent-inject-secret-dbcreds.txt: "secret/data/myapp/database"
    spec:
      serviceAccountName: myapp-sa
      containers:
      - name: nginx-container
        image: nginx:bookworm-otel
        ports:
        - containerPort: 80
