apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: postgres-bitnami
spec:
  project: default
  source:
    repoURL: https://charts.bitnami.com/bitnami
    chart: postgresql
    # targetRevision: 18.6.0
    # targetRevision: 18.5.24
    targetRevision: 18.5.24
    helm:
      values: |
        architecture: standalone
        auth:
          postgresPassword: mysecurepassword
          username: myuser
          password: myuserpassword
          database: mydatabase
        primary:
          persistence:
            enabled: true
            size: 8Gi
  destination:
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true