apiVersion: batch/v1
kind: CronJob
metadata:
  labels:
    chart: cronjobs-0.1.0
  name: health-check-5-minutes
spec:
  #schedule: "*/5 * * * *"
  schedule: "* * * * *"
  concurrencyPolicy: Forbid
  jobTemplate:
    spec:
      backoffLimit: 0 
      template:
        spec:
          serviceAccountName: deployment-checker
          containers:
          - name: health-check-5-minutes
            image: bitnami/kubectl:latest
            imagePullPolicy: IfNotPresent
            env:
            - name: NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: DEPLOYMENT_NAME
              value: nginx-deployment
            command:
            - /bin/sh
            - -c
            - |
              echo "Asking Kubernetes API for the status of ${DEPLOYMENT_NAME}..."
              
              # How many replicas are fully available and ready?
              AVAILABLE_REPLICAS=$(kubectl get deployment ${DEPLOYMENT_NAME} -n ${NAMESPACE} -o jsonpath='{.status.availableReplicas}')
              
              # If the result is empty or 0, the app is down.
              if [ -z "$AVAILABLE_REPLICAS" ] || [ "$AVAILABLE_REPLICAS" = "0" ]; then
                echo "FAILED: Deployment has 0 available replicas."
                exit 1
              else
                echo "OK: Deployment is healthy and running with ${AVAILABLE_REPLICAS} available replica(s)."
                exit 0
              fi
          restartPolicy: Never