apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization


resources:
  - cron-job.yaml
  - nginx/nginx-deployment.yaml
  - nginx/nginx-svc.yaml
  - postgres/statefulset.yaml
  - postgres/service.yaml
  - postgres/configmap.yaml
  - postgres/secret.yaml
  - rbac/health-check-rbac.yaml
  - rbac/vault-sa.yaml