pipeline {
    agent any
    
    environment {
        IMAGE_NAME = "nginx"
        IMAGE_TAG = "1.67.0" 
        
        GIT_CREDS_ID = "git-token"
        REPO_URL = "https://github.com/EvanLei-git/argocd-examples.git"
    }

    triggers {
        pollSCM('* * * * *')
    }
    
    stages {
        stage('Setup Tools') {
            steps {
                
                sh 'curl -s "https://raw.githubusercontent.com/kubernetes-sigs/kustomize/master/hack/install_kustomize.sh" | bash'
            }
        }
        
        stage('Update GitOps Repo') {
            steps {
                git branch: 'kustomize', credentialsId: "${GIT_CREDS_ID}", url: "${REPO_URL}"
                
                dir('examples/overlays/dev') {
                    sh "${WORKSPACE}/kustomize edit set image ${IMAGE_NAME}=${IMAGE_NAME}:${IMAGE_TAG}"
                }
            }
        }
        stage('Commit to Trigger ArgoCD') {
            steps {
                withCredentials([usernamePassword(credentialsId: "${GIT_CREDS_ID}", usernameVariable: 'GIT_USER', passwordVariable: 'GIT_PASS')]) {
                    // Notice the single quotes below!
                    sh '''
                        git config user.name "Jenkins CI"
                        git config user.email "ci@jenkins.local"
                        git add examples/overlays/dev/kustomization.yaml
                        git commit -m "ci: update dev nginx image to ${IMAGE_TAG}"
                        
                        # Push back to GitHub
                        git push https://${GIT_USER}:${GIT_PASS}@github.com/EvanLei-git/argocd-examples.git HEAD:kustomize
                    '''
                }
            }
        }
    }
}