apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: vault
  namespace: argocd
spec:
  project: default
  # Use 'sources' (plural) to pull from two places at once
  sources:
    # Source 1: The official public HashiCorp Helm Chart
    - chart: vault
      repoURL: https://helm.releases.hashicorp.com
      targetRevision: 0.32.0 # Replace with your desired Vault Helm chart version
      helm:
        valueFiles:
          # $values tells ArgoCD to look in the other Git repo referenced below!
          - $values/hashicorp/vault-values.yaml

    # Source 2: Your PRIVATE Git repository holding the values file
    - repoURL: https://github.com/EvanLei-git/git-ops-setup.git
      targetRevision: main
      # The 'ref: values' acts as a variable name that the Helm chart source above uses
      ref: values

  destination:
    server: https://kubernetes.default.svc
    namespace: vault # Vault usually lives in its own namespace
  
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true