apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: wordpress
resources:
  - ../../base/mariadb
  - db-init-configmap.yaml
  - vault-auth-config.yaml
  - vault-secret-sync.yaml
  - mariadb-backup-pvc.yaml
  - mariadb-backup-cronjob.yaml