apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: mariadb-vault-sync
  namespace: wordpress
spec:
  vaultAuthRef: mariadb-vault-auth
  type: kv-v2
  mount: secret
  path: mariadb
  destination:
    name: mariadb-credentials
    create: true
