apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultConnection
metadata:
  name: mariadb-vault-connection
  namespace: wordpress
spec:
  address: http://vault.vault.svc.cluster.local:8200
---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultAuth
metadata:
  name: mariadb-vault-auth
  namespace: wordpress
spec:
  method: kubernetes
  mount: kubernetes
  kubernetes:
    role: db-secrets-role
    serviceAccount: default
  vaultConnectionRef: mariadb-vault-connection
