apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "norbloc-helm.fullname" . }}-configmap
  labels:
    {{- include "norbloc-helm.labels" . | nindent 4 }}
data:
  MYSQL_DATABASE: {{ .Values.mariadb.database | quote }}
  WORDPRESS_DB_HOST: {{ include "norbloc-helm.fullname" . }}-mariadb
