apiVersion: v1
kind: Secret
metadata:
  name: {{ include "norbloc-helm.fullname" . }}-mariadb-credentials
  labels:
    {{- include "norbloc-helm.labels" . | nindent 4 }}
type: Opaque
data:
  MYSQL_ROOT_PASSWORD: {{ .Values.mariadb.auth.rootPassword | quote }}
  MYSQL_USER: {{ .Values.mariadb.auth.user | b64enc | quote }}
  MYSQL_PASSWORD: {{ .Values.mariadb.auth.userPassword | quote }}
