{{- $fullName := include "norbloc-helm.fullname" . -}}
{{- $ns := .Values.namespace | default .Release.Namespace -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ $fullName }}-mariadb-credentials
  namespace: {{ $ns }}
  labels:
    {{- include "norbloc-helm.labels" . | nindent 4 }}
type: Opaque
data:
  # Used by MariaDB container (MARIADB_ROOT_PASSWORD, MARIADB_USER, MARIADB_PASSWORD)
  MYSQL_ROOT_PASSWORD: {{ .Values.mariadb.auth.rootPassword | b64enc | quote }}
  MYSQL_USER: {{ .Values.mariadb.auth.user | b64enc | quote }}
  MYSQL_PASSWORD: {{ .Values.mariadb.auth.userPassword | b64enc | quote }}
