apiVersion: v1
kind: Service
metadata:
  name: {{ include "norbloc-helm.fullname" . }}-wordpress
  labels:
    app.kubernetes.io/component: wordpress
    {{- include "norbloc-helm.labels" . | nindent 4 }}
spec:
  type: {{ .Values.wordpress.service.type }}
  selector:
    app.kubernetes.io/component: wordpress
    {{- include "norbloc-helm.selectorLabels" . | nindent 4 }}
  ports:
    - port: {{ .Values.wordpress.service.port }}
      targetPort: 80
      protocol: TCP
