apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization


resources:
  - ../../base
  - namespace.yaml

namePrefix: dev-

# Sets the namespace for all generated resources (probably need to change this)
namespace: dev-env


# SEPARATE NAMESPACES
patches:
  - target:
      kind: Application
      name: postgres-bitnami
    patch: |-
      - op: replace
        path: /spec/destination/namespace
        value: dev-env


images:
  - name: nginx        # Match ONLY the name part of the image wihtout the bookworm-otel
    newTag: "stable-bookworm-otel"   # This will replace "bookworm-otel" with "v1.0.0"

# helmCharts:
#   - name: postgresql
#     repo: https://charts.bitnami.com/bitnami
#     version: 18.5.18
#     releaseName: postgres-bitnami
#     # Same values 
#     valuesInline: 
#       auth:
#         postgresPassword: mysecurepassword
#         username: myuser
#         password: myuserpassword
#         database: mydatabase
#       primary:
#         persistence:
#           enabled: true
#           size: 8Gi