apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization


resources:
- ../../base
- namespace.yaml

namePrefix: dev-

# Sets the namespace for all generated resources (probably need to change this)
namespace: dev-env



# SEPARATE NAMESPACES

# 1. The argocd Namespace gets:
# The postgres-bitnami Application object (the instruction ticket).

# 2. The dev-env Namespace gets EVERYTHING else:
# The actual PostgreSQL database pods
# The PostgreSQL services and volume claims
# The NGINX deployment and pods
# The NGINX service

patches:
- patch: |-
    - op: replace
      path: /spec/destination/namespace
      value: dev-env
    - op: replace
      path: /metadata/namespace
      value: argocd
  target:
    kind: Application
    name: postgres-bitnami


images:
- name: nginx
  newName: nginx
  newTag: 1.29.8
